version: "3.4"

services:
  django:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:80 && python manage.py runserver 0.0.0.0:443"
    volumes:
      - .:/app
    ports:
      - "80:80"
      - "443:443"
    tty: true
    stdin_open: true
    dns:
      - 8.8.8.8
    expose:
      - 80
      - 443
