# Generated by Django 3.0.3 on 2020-08-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userform',
            name='Product_Name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
